name: Deploy to AWS ECR and ECS

on:
  push:
    branches: [ "main" ]
#llllll
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: simplehelloapi
        run: |
          set -e
          echo "Checking if ECR repository '$ECR_REPOSITORY' exists in region $AWS_REGION..."
          if ! aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" >/dev/null 2>&1; then
            echo "Repository not found. Creating ECR repository '$ECR_REPOSITORY' in $AWS_REGION"
            aws ecr create-repository --repository-name "$ECR_REPOSITORY" --region "$AWS_REGION"
          else
            echo "ECR repository '$ECR_REPOSITORY' already exists."
          fi

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simplehelloapi    # <-- el nombre de tu repositorio en ECR
          IMAGE_TAG: latest
        run: |
          set -e
          echo "Verificando existencia del Dockerfile..."
          test -f simplehelloapi/Dockerfile || (echo "ERROR: No se encontrÃ³ Dockerfile en simplehelloapi/Dockerfile" && exit 1)
          echo "Building image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f simplehelloapi/Dockerfile simplehelloapi
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG